
development:
  adapter: postgresql
  encoding: unicode
  database: brbn_app_development
  pool: 5
  username: Olly
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: brbn_app_test
  pool: 5
  username: Olly
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: brbn_app_production
  pool: 5
  username: Olly
  password:
